<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HRWINLI3927" failures="1" tests="2" name="com.hub.testcases.HUBLoginTests" time="86.013" errors="0" timestamp="27 Jan 2022 10:04:38 GMT" skipped="0">
  <testcase classname="com.hub.testcases.HUBLoginTests" name="loginTest" time="69.604"/>
  <testcase classname="com.hub.testcases.HUBLoginTests" name="loginTest" time="16.409">
    <failure message="
expected: &quot;HungerRush HUB | Dashboard&quot;
 but was: &quot;HungerRush HUB | LogOn&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
expected: "HungerRush HUB | Dashboard"
 but was: "HungerRush HUB | LogOn"
at com.hub.testcases.HUBLoginTests.loginTest(HUBLoginTests.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- com.hub.testcases.HUBLoginTests -->
